"""Phase 2 rig builder for Warrior_V0.

Run this in the Blender file generated by create_warrior_v0.py.

Coordinate convention
---------------------
Blender: Z is up and the warrior faces -Y (the chest plate/front of boots).
glTF/Godot: Blender's -Y forward is converted to Godot's conventional -Z forward.
Scale: 1 Blender unit = 1 metre.

This segmented low-poly character uses rigid bone parenting. This is intentional:
it preserves the Phase 1 silhouette and prevents armor/limb pieces from collapsing.
"""

import bpy
import math
from mathutils import Vector, Matrix


SOURCE_COLLECTION = "Warrior_V0"
BACKUP_COLLECTION = "Warrior_V0_Backup"
RIG_COLLECTION = "Warrior_Rigged_V1"
ARMATURE_NAME = "WarriorSkeleton"


EXPECTED_OBJECTS = {
    "Head", "Hair", "Neck", "Torso", "ChestArmor", "Waist", "Belt", "Buckle",
    "ShoulderArmor_L", "ShoulderArmor_R", "UpperArm_L", "UpperArm_R",
    "Forearm_L", "Forearm_R", "Hand_L", "Hand_R", "Hips", "Thigh_L",
    "Thigh_R", "Shin_L", "Shin_R", "Boot_L", "Boot_R", "Sword_Blade",
    "Sword_Guard", "Sword_Handle", "Sword_Pommel",
}


def object_center(obj):
    return sum((obj.matrix_world @ Vector(corner) for corner in obj.bound_box), Vector()) / 8.0


def bounds_world(obj):
    points = [obj.matrix_world @ Vector(corner) for corner in obj.bound_box]
    return Vector(map(min, zip(*points))), Vector(map(max, zip(*points)))


def remove_collection_tree(collection):
    """Remove only a previous generated V1 tree; never touches Warrior_V0."""
    for child in list(collection.children):
        remove_collection_tree(child)
    for obj in list(collection.objects):
        bpy.data.objects.remove(obj, do_unlink=True)
    bpy.data.collections.remove(collection)


def link_only(obj, collection):
    for old in list(obj.users_collection):
        old.objects.unlink(obj)
    collection.objects.link(obj)


def duplicate_object(obj, collection, suffix=""):
    copy = obj.copy()
    if obj.data:
        copy.data = obj.data.copy()
    copy.name = obj.name + suffix
    collection.objects.link(copy)
    copy.matrix_world = obj.matrix_world.copy()
    copy.animation_data_clear()
    return copy


def make_backup(source):
    old = bpy.data.collections.get(BACKUP_COLLECTION)
    if old:
        remove_collection_tree(old)
    backup = bpy.data.collections.new(BACKUP_COLLECTION)
    bpy.context.scene.collection.children.link(backup)
    for obj in source.objects:
        duplicate_object(obj, backup, "_Backup")
    backup.hide_viewport = True
    backup.hide_render = True
    return backup


def make_rig_collections():
    old = bpy.data.collections.get(RIG_COLLECTION)
    if old:
        remove_collection_tree(old)
    root = bpy.data.collections.new(RIG_COLLECTION)
    bpy.context.scene.collection.children.link(root)
    children = {}
    for name in ("Body", "Armor", "Accessories", "Sword"):
        children[name] = bpy.data.collections.new(name)
        root.children.link(children[name])
    return root, children


def classify(name):
    if name.startswith("Sword_"):
        return "Sword"
    if name in {"ChestArmor", "ShoulderArmor_L", "ShoulderArmor_R", "Shin_L", "Shin_R"}:
        return "Armor"
    if name in {"Hair", "Belt", "Buckle"}:
        return "Accessories"
    return "Body"


def duplicate_working_model(source, subcollections):
    result = {}
    for obj in source.objects:
        if obj.name not in EXPECTED_OBJECTS:
            continue
        result[obj.name] = duplicate_object(obj, subcollections[classify(obj.name)])
    return result


def add_bone(edit_bones, name, head, tail, parent=None, connected=False, deform=True):
    bone = edit_bones.new(name)
    bone.head = head
    bone.tail = tail
    bone.roll = 0.0
    bone.use_deform = deform
    if parent:
        bone.parent = edit_bones[parent]
        bone.use_connect = connected
    return bone


def create_armature(objects, rig_collection):
    """Build bones from measured centers/joints of the actual Phase 1 geometry."""
    center = {name: object_center(obj) for name, obj in objects.items()}
    arm_data = bpy.data.armatures.new(ARMATURE_NAME)
    armature = bpy.data.objects.new(ARMATURE_NAME, arm_data)
    rig_collection.objects.link(armature)
    armature.show_in_front = True
    armature.data.display_type = 'OCTAHEDRAL'

    bpy.context.view_layer.objects.active = armature
    armature.select_set(True)
    bpy.ops.object.mode_set(mode='EDIT')
    eb = arm_data.edit_bones

    # Central chain, derived from the measured pelvis, torso, neck and head.
    hip = center["Hips"]
    torso = center["Torso"]
    neck = center["Neck"]
    head = center["Head"]
    add_bone(eb, "Root", (0, 0, 0.02), (0, 0, 0.16), deform=False)
    add_bone(eb, "Hips", (hip.x, hip.y, hip.z - 0.08), (hip.x, hip.y, 1.02), "Root")
    add_bone(eb, "Spine", (0, 0, 1.02), (0, 0, torso.z), "Hips", True)
    add_bone(eb, "Chest", (0, 0, torso.z), (0, 0, 1.38), "Spine", True)
    add_bone(eb, "UpperChest", (0, 0, 1.38), (0, 0, neck.z), "Chest", True)
    add_bone(eb, "Neck", (0, 0, neck.z), (0, 0, head.z - 0.08), "UpperChest", True)
    add_bone(eb, "Head", (0, 0, head.z - 0.08), (0, -0.01, head.z + 0.22), "Neck", True)

    # Arm joints use the exact endpoints used by the Phase 1 meshes.
    for side, sign in (("L", 1.0), ("R", -1.0)):
        shoulder = Vector((0.34 * sign, 0.0, 1.40))
        elbow = Vector((0.59 * sign, 0.0, 1.25))
        wrist = Vector((0.79 * sign, 0.0, 1.13))
        hand_end = Vector((0.93 * sign, 0.0, 1.05))
        add_bone(eb, f"Shoulder_{side}", (0, 0, 1.43), shoulder, "UpperChest")
        add_bone(eb, f"UpperArm_{side}", shoulder, elbow, f"Shoulder_{side}", True)
        add_bone(eb, f"Forearm_{side}", elbow, wrist, f"UpperArm_{side}", True)
        add_bone(eb, f"Hand_{side}", wrist, hand_end, f"Forearm_{side}", True)

    # Leg chains are based on thigh/shin contact points and the actual boot direction.
    for side, sign in (("L", 1.0), ("R", -1.0)):
        upper = Vector((0.17 * sign, 0.0, 0.88))
        knee = Vector((0.19 * sign, 0.0, 0.55))
        ankle = Vector((0.205 * sign, 0.0, 0.23))
        ball = Vector((0.205 * sign, -0.17, 0.10))
        toe = Vector((0.205 * sign, -0.29, 0.08))
        add_bone(eb, f"Thigh_{side}", upper, knee, "Hips")
        add_bone(eb, f"Shin_{side}", knee, ankle, f"Thigh_{side}", True)
        add_bone(eb, f"Foot_{side}", ankle, ball, f"Shin_{side}", True)
        add_bone(eb, f"Toe_{side}", ball, toe, f"Foot_{side}", True)

    # Socket follows Hand_R. Its placement matches the existing sword grip.
    add_bone(eb, "WeaponSocket_R", (-0.93, 0.0, 1.10), (-1.00, 0.0, 1.20), "Hand_R", deform=False)

    # Lightweight animator controls. They are non-deforming and export-safe as bones.
    for side, sign in (("L", 1.0), ("R", -1.0)):
        add_bone(eb, f"FootIK_{side}", (0.205 * sign, -0.17, 0.10),
                 (0.205 * sign, -0.17, 0.25), "Root", deform=False)
        add_bone(eb, f"KneePole_{side}", (0.19 * sign, -0.45, 0.55),
                 (0.19 * sign, -0.45, 0.68), "Root", deform=False)
        add_bone(eb, f"HandIK_{side}", (0.93 * sign, 0.0, 1.05),
                 (1.05 * sign, 0.0, 1.00), "Root", deform=False)
        add_bone(eb, f"ElbowPole_{side}", (0.59 * sign, -0.42, 1.25),
                 (0.59 * sign, -0.42, 1.38), "Root", deform=False)

    bpy.ops.object.mode_set(mode='POSE')
    # IK is supplied but disabled by default so clean FK/rest behavior is guaranteed.
    # Animators can enable the named constraints when useful and bake before glTF export.
    for side in ("L", "R"):
        leg_ik = armature.pose.bones[f"Shin_{side}"].constraints.new('IK')
        leg_ik.name = f"Optional_Foot_IK_{side}"
        leg_ik.target = armature
        leg_ik.subtarget = f"FootIK_{side}"
        leg_ik.pole_target = armature
        leg_ik.pole_subtarget = f"KneePole_{side}"
        leg_ik.chain_count = 2
        leg_ik.mute = True
        arm_ik = armature.pose.bones[f"Forearm_{side}"].constraints.new('IK')
        arm_ik.name = f"Optional_Hand_IK_{side}"
        arm_ik.target = armature
        arm_ik.subtarget = f"HandIK_{side}"
        arm_ik.pole_target = armature
        arm_ik.pole_subtarget = f"ElbowPole_{side}"
        arm_ik.chain_count = 2
        arm_ik.mute = True
    bpy.ops.object.mode_set(mode='OBJECT')
    armature.select_set(False)
    return armature


def bone_parent_keep_transform(obj, armature, bone_name):
    world = obj.matrix_world.copy()
    obj.parent = armature
    obj.parent_type = 'BONE'
    obj.parent_bone = bone_name
    obj.matrix_world = world
    obj["rig_binding"] = "RIGID_BONE_PARENT"
    obj["bound_bone"] = bone_name


def bind_model(objects, armature, sword_collection):
    bindings = {
        "Head": "Head", "Hair": "Head", "Neck": "Neck",
        "Torso": "Spine", "ChestArmor": "Chest", "Waist": "Hips",
        "Belt": "Hips", "Buckle": "Hips", "Hips": "Hips",
        "ShoulderArmor_L": "UpperArm_L", "ShoulderArmor_R": "UpperArm_R",
        "UpperArm_L": "UpperArm_L", "UpperArm_R": "UpperArm_R",
        "Forearm_L": "Forearm_L", "Forearm_R": "Forearm_R",
        "Hand_L": "Hand_L", "Hand_R": "Hand_R",
        "Thigh_L": "Thigh_L", "Thigh_R": "Thigh_R",
        "Shin_L": "Shin_L", "Shin_R": "Shin_R",
        "Boot_L": "Foot_L", "Boot_R": "Foot_R",
    }
    for object_name, bone_name in bindings.items():
        bone_parent_keep_transform(objects[object_name], armature, bone_name)

    sword_root = bpy.data.objects.new("Sword", None)
    sword_collection.objects.link(sword_root)
    sword_root.empty_display_type = 'ARROWS'
    sword_root.empty_display_size = 0.18
    sword_root.matrix_world = Matrix.Translation(Vector((-1.0, 0.0, 1.10)))
    bone_parent_keep_transform(sword_root, armature, "WeaponSocket_R")
    for name in ("Sword_Blade", "Sword_Guard", "Sword_Handle", "Sword_Pommel"):
        world = objects[name].matrix_world.copy()
        objects[name].parent = sword_root
        objects[name].matrix_world = world
        objects[name]["rig_binding"] = "RIGID_SWORD_CONTAINER"
    return bindings, sword_root


def run_pose_tests(armature, objects):
    """Exercise major FK chains, verify sword following, then restore rest/A-pose."""
    bpy.context.view_layer.objects.active = armature
    armature.select_set(True)
    bpy.ops.object.mode_set(mode='POSE')
    tests = [
        ("UpperArm_R", 'Y', math.radians(45)),
        ("Forearm_R", 'Y', math.radians(90)),
        ("UpperArm_L", 'Y', math.radians(-45)),
        ("Forearm_L", 'Y', math.radians(-90)),
        ("Shin_L", 'X', math.radians(55)),
        ("Shin_R", 'X', math.radians(55)),
        ("Chest", 'Z', math.radians(18)),
        ("Head", 'Z', math.radians(28)),
    ]
    for bone_name, axis, angle in tests:
        pb = armature.pose.bones[bone_name]
        pb.rotation_mode = 'XYZ'
        setattr(pb.rotation_euler, axis.lower(), angle)
    bpy.context.view_layer.update()
    sword_before_reset = objects["Sword_Blade"].matrix_world.copy()
    sword_followed = not sword_before_reset.is_identity

    # Clear every test transform. No actions/keyframes are created or retained.
    for pb in armature.pose.bones:
        pb.location = (0, 0, 0)
        pb.rotation_mode = 'QUATERNION'
        pb.rotation_quaternion = (1, 0, 0, 0)
        pb.scale = (1, 1, 1)
    bpy.context.view_layer.update()
    bpy.ops.object.mode_set(mode='OBJECT')
    armature.select_set(False)
    return sword_followed


def validate(armature, objects, bindings, sword_root, pose_test_passed):
    required_bones = {
        "Root", "Hips", "Spine", "Chest", "UpperChest", "Neck", "Head",
        "Shoulder_L", "UpperArm_L", "Forearm_L", "Hand_L",
        "Shoulder_R", "UpperArm_R", "Forearm_R", "Hand_R",
        "Thigh_L", "Shin_L", "Foot_L", "Toe_L",
        "Thigh_R", "Shin_R", "Foot_R", "Toe_R", "WeaponSocket_R",
    }
    bones = armature.data.bones
    missing = sorted(required_bones - set(bones.keys()))

    def chain_ok(names):
        return all(bones[names[i]].parent == bones[names[i - 1]] for i in range(1, len(names)))

    values = [p for obj in objects.values() if obj.type == 'MESH' for corner in obj.bound_box
              for p in [obj.matrix_world @ Vector(corner)]]
    minimum_z = min(point.z for point in values)
    scales_ok = all(abs(value - 1.0) < 0.001 for value in armature.scale)
    rigid_ok = all(objects[name].parent == armature and objects[name].parent_bone == bone
                   for name, bone in bindings.items())
    sword_ok = (sword_root.parent == armature and sword_root.parent_bone == "WeaponSocket_R"
                and all(objects[n].parent == sword_root for n in
                        ("Sword_Blade", "Sword_Guard", "Sword_Handle", "Sword_Pommel")))

    print("\n=== WARRIOR RIG VALIDATION ===")
    print("Skeleton created:", "PASS" if armature else "FAIL")
    print("Root bone found:", "PASS" if "Root" in bones else "FAIL")
    print("Hips found:", "PASS" if "Hips" in bones else "FAIL")
    print("Left arm hierarchy:", "PASS" if chain_ok(["Shoulder_L", "UpperArm_L", "Forearm_L", "Hand_L"]) else "FAIL")
    print("Right arm hierarchy:", "PASS" if chain_ok(["Shoulder_R", "UpperArm_R", "Forearm_R", "Hand_R"]) else "FAIL")
    print("Left leg hierarchy:", "PASS" if chain_ok(["Thigh_L", "Shin_L", "Foot_L", "Toe_L"]) else "FAIL")
    print("Right leg hierarchy:", "PASS" if chain_ok(["Thigh_R", "Shin_R", "Foot_R", "Toe_R"]) else "FAIL")
    print("Weapon socket:", "PASS" if "WeaponSocket_R" in bones else "FAIL")
    print("Sword parented:", "PASS" if sword_ok else "FAIL")
    print("Mesh armature binding:", "PASS" if rigid_ok else "FAIL", "(rigid segmented binding)")
    print("Pose tests and reset:", "PASS" if pose_test_passed else "WARNING")
    print("Scale valid:", "PASS" if scales_ok else "FAIL")
    print("Character above ground:", "PASS" if minimum_z >= -0.001 else "FAIL", f"(min Z={minimum_z:.4f})")
    print("Missing bones:", "NONE" if not missing else ", ".join(missing))
    print("Warnings:")
    print("- Optional IK constraints are muted by default; enable and bake before glTF export if used.")
    print("- Segmented meshes use rigid bone parenting; no deform weights are needed or generated.")
    print("=== END VALIDATION ===\n")
    return not missing and rigid_ok and sword_ok and scales_ok and minimum_z >= -0.001


def main():
    if bpy.context.object and bpy.context.object.mode != 'OBJECT':
        bpy.ops.object.mode_set(mode='OBJECT')
    source = bpy.data.collections.get(SOURCE_COLLECTION)
    if not source:
        raise RuntimeError("Warrior_V0 collection not found. Open Warrior_V0.blend first.")
    source_names = {obj.name for obj in source.objects}
    missing_objects = sorted(EXPECTED_OBJECTS - source_names)
    if missing_objects:
        raise RuntimeError("Warrior_V0 is incomplete. Missing: " + ", ".join(missing_objects))

    print("Inspected Warrior_V0 objects:", ", ".join(sorted(source_names)))
    make_backup(source)
    rig_collection, subcollections = make_rig_collections()
    objects = duplicate_working_model(source, subcollections)
    armature = create_armature(objects, rig_collection)
    bindings, sword_root = bind_model(objects, armature, subcollections["Sword"])
    pose_ok = run_pose_tests(armature, objects)
    valid = validate(armature, objects, bindings, sword_root, pose_ok)

    source.hide_viewport = True
    source.hide_render = True
    bpy.context.view_layer.objects.active = armature
    armature.select_set(True)
    armature["front_direction_blender"] = "-Y"
    armature["front_direction_godot"] = "-Z after glTF conversion"
    armature["unit_scale"] = "1 BU = 1 metre"
    armature["phase"] = "Warrior Rig Phase 2"
    print("Warrior_Rigged_V1 complete.", "VALID" if valid else "CHECK WARNINGS")


if __name__ == "__main__":
    main()
